# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Focused on the 1.8.9 (Ornithe) module only.
# Set additional axolotlclient.modules.<version>=true entries (or axolotlclient.modules.all=true) to build more versions.
axolotlclient.modules.1.8.9=true

# Mod Properties
version=3.2.2-alpha.1
maven_group=io.github.axolotlclient
archives_base_name=AxolotlClient

# Shared Dependencies
fabric_loader=0.19.3
config=3.1.16
