# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# 1.8.9 (Ornithe) is the only supported Minecraft version.

# Mod Properties
version=1.0.0
maven_group=io.github.axolotlclient
archives_base_name=DolphinClient

# Shared Dependencies
fabric_loader=0.19.3
config=3.1.16
