pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Ornithe'
			url = 'https://maven.ornithemc.net/releases'
		}
		maven {
			name = 'Ornithe Snapshots'
			url = 'https://maven.ornithemc.net/snapshots'
		}
		gradlePluginPortal()
	}
}

rootProject.name = "DolphinClient-mod"
include 'common'
include '1.8.9'
project(':1.8.9').projectDir = file('versions/1.8.9')
